export const getMockdata = ()=> {
    return [
        {name:"北京",value:396},
        {name:"天津",value:131},
        {name:"河北",value:308},
        {name:"山西",value:132},
        {name:"内蒙古",value:75},
        {name:"辽宁",value:121},
        {name:"吉林",value:91},
        {name:"黑龙江",value:479},
        {name:"上海",value:334},
        {name:"江苏",value:631},
        {name:"浙江",value:1203},
        {name:"安徽",value:988},
        {name:"福建",value:293},
        {name:"江西",value:934},
        {name:"山东",value:748},
        {name:"河南",value:1267},
        {name:"湖北",value:62662},
        {name:"湖南",value:1011},
        {name:"广东",value:1333},
        {name:"广西",value:246},
        {name:"海南",value:168},
        {name:"重庆",value:567},
        {name:"四川",value:525},
        {name:"贵州",value:146},
        // {name:"云南",value:174},
        {name:"西藏",value:1},
        {name:"陕西",value:245},
        {name:"甘肃",value:91},
        {name:"青海",value:18},
        {name:"宁夏",value:71},
        {name:"新疆",value:76},
        {name:"台湾",value:24},
        {name:"香港",value:68},
        {name:"澳门",value:10}
    ]
}

export const getMockToolData = ()=> {
    return [
        {name:"北京",value:[{name:"确诊",value:396},{name:"疑似",value:114},{name:"死亡",value:4}]},
        {name:"天津",value:[{name:"确诊",value:131},{name:"疑似",value:173},{name:"死亡",value:3}]},
        {name:"河北",value:[{name:"确诊",value:308},{name:"疑似",value:0},{name:"死亡",value:5}]},
        {name:"山西",value:[{name:"确诊",value:132},{name:"疑似",value:11},{name:"死亡",value:0}]},
        {name:"内蒙古",value:[{name:"确诊",value:75},{name:"疑似",value:16},{name:"死亡",value:0}]},
        {name:"辽宁",value:[{name:"确诊",value:121},{name:"疑似",value:77},{name:"死亡",value:1}]},
        {name:"吉林",value:[{name:"确诊",value:91},{name:"疑似",value:18},{name:"死亡",value:1}]},
        {name:"黑龙江",value:[{name:"确诊",value:479},{name:"疑似",value:1},{name:"死亡",value:12}]},
        {name:"上海",value:[{name:"确诊",value:334},{name:"疑似",value:107},{name:"死亡",value:2}]},
        {name:"江苏",value:[{name:"确诊",value:631},{name:"疑似",value:12},{name:"死亡",value:0}]},
        {name:"浙江",value:[{name:"确诊",value:1203},{name:"疑似",value:26},{name:"死亡",value:1}]},
        {name:"安徽",value:[{name:"确诊",value:988},{name:"疑似",value:7},{name:"死亡",value:6}]},
        {name:"福建",value:[{name:"确诊",value:293},{name:"疑似",value:6},{name:"死亡",value:1}]},
        {name:"江西",value:[{name:"确诊",value:934},{name:"疑似",value:2},{name:"死亡",value:1}]},
        {name:"山东",value:[{name:"确诊",value:748},{name:"疑似",value:30},{name:"死亡",value:4}]},
        {name:"河南",value:[{name:"确诊",value:1267},{name:"疑似",value:103},{name:"死亡",value:19}]},
        {name:"湖北",value:[{name:"确诊",value:62662},{name:"疑似",value:4094},{name:"死亡",value:2144}]},
        {name:"湖南",value:[{name:"确诊",value:1011},{name:"疑似",value:7},{name:"死亡",value:4}]},
        {name:"广东",value:[{name:"确诊",value:1333},{name:"疑似",value:1},{name:"死亡",value:5}]},
        {name:"广西",value:[{name:"确诊",value:246},{name:"疑似",value:67},{name:"死亡",value:2}]},
        {name:"海南",value:[{name:"确诊",value:168},{name:"疑似",value:59},{name:"死亡",value:4}]},
        {name:"重庆",value:[{name:"确诊",value:567},{name:"疑似",value:71},{name:"死亡",value:6}]},
        {name:"四川",value:[{name:"确诊",value:525},{name:"疑似",value:56},{name:"死亡",value:3}]},
        {name:"贵州",value:[{name:"确诊",value:146},{name:"疑似",value:11},{name:"死亡",value:2}]},
        // {name:"云南",value:[{name:"确诊",value:174},{name:"疑似",value:58},{name:"死亡",value:2}]},
        {name:"西藏",value:[{name:"确诊",value:1},{name:"疑似",value:0},{name:"死亡",value:0}]},
        {name:"陕西",value:[{name:"确诊",value:245},{name:"疑似",value:46},{name:"死亡",value:1}]},
        {name:"甘肃",value:[{name:"确诊",value:91},{name:"疑似",value:1},{name:"死亡",value:2}]},
        {name:"青海",value:[{name:"确诊",value:18},{name:"疑似",value:0},{name:"死亡",value:0}]},
        {name:"宁夏",value:[{name:"确诊",value:71},{name:"疑似",value:21},{name:"死亡",value:0}]},
        {name:"新疆",value:[{name:"确诊",value:76},{name:"疑似",value:11},{name:"死亡",value:1}]},
        {name:"台湾",value:[{name:"确诊",value:24},{name:"疑似",value:0},{name:"死亡",value:1}]},
        {name:"香港",value:[{name:"确诊",value:68},{name:"疑似",value:0},{name:"死亡",value:2}]},
        {name:"澳门",value:[{name:"确诊",value:10},{name:"疑似",value:0},{name:"死亡",value:0}]}
    ]
}
